Add pip requirements

diff --git a/install b/install
--- a/install
+++ b/install
@@ -24,6 +24,11 @@ install_ros
 [ $? -eq 0 ] || error "Failed to install ROS, aborting..."
 echo -e "${GREEN}ROS installation done${NOCOLOR}"
 
+echo -e "${BLUE}Installing pip modules${NOCOLOR}"
+python3 -m pip install -r requirements.txt
+[ $? -eq 0 ] || echo "${RED}Failed install pip modules, continuing...${NOCLOR}"
+echo -e "${GREEN}Pip modules installaion done${NOCOLOR}"
+
 read -p "Do you wish to install simulator (Gazebo) [Y/n]" -n 1 -s ans && echo
 [ "${ans}" != "n" ] && install_gazebo
 echo -e "${GREEN}Gazebo installation done${NOCOLOR}"
